# Generated by Django 4.2.23 on 2025-06-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer_api', '0001_initial'),
    ]

    operations = [
    ]
