# Generated by Django 4.2.23 on 2025-07-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer_api', '0002_link_existing_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidates',
        ),
        migrations.AlterModelTable(
            name='interviewdetail',
            table='interview_details',
        ),
        migrations.AlterModelTable(
            name='interviewinvitation',
            table='interview_invitation',
        ),
    ]
